# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171128_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='can_drink',
        ),
    ]
